---
numberOfDaysToSearch: 7
healthcheck:
  workingText: "WORKING"
elasticsearch:
  host: "http://localhost:9123"
  sniff: false
  indexMappings:
    chat: '{ "mappings": { "message":{}}}'
cassandra:
  hosts: "localhost:9042"
  keyspace: "chat"
  bucket:
    sizeInDays: 1
    startDate: "01-01-2018"
  messages:
    limit: 10
mongo:
  host: "mongodb://localhost:27017"
  allow_anonymous: false
  database: "mqtt"
logger:
  level: "debug"
jaeger:
  disabled: false
  samplingProbability: 1.0
extensions:
  dogstatsd:
    host: localhost:8125
    prefix: mqtthistory.
    tags_prefix: ""
    rate: 1
